### ISSUE TITLE
ModuleNotFoundError: No module named 'lib.infer_pack'

### ISSUE THREAD

**Issue by mopoIo** [Snowad14/IAStreameur#2]
```
Could not find module 'C:\Users\gabri\AppData\Local\Programs\Python\Python310\Lib\site-packages\xformers\_C.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
2023-09-21 23:57:06 | WARNING | root | WARNING: Could not find module 'C:\Users\gabri\AppData\Local\Programs\Python\Python310\Lib\site-packages\xformers\_C.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
Need to compile C++ extensions to get sparse attention suport. Please run python setup.py build develop
2023-09-21 23:57:06 | WARNING | root | Triton is not available, some optimizations will not be enabled.
This is just a warning: No module named 'triton'
2023-09-21 23:57:06 | WARNING | root | A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Traceback (most recent call last):
  File "C:\Users\gabri\Desktop\IAStreameur-main\main.py", line 8, in <module>
    from ttsEngine import gen_elevenlabs, gen_RVC, gen_Edge, gen_VITS
  File "C:\Users\gabri\Desktop\IAStreameur-main\ttsEngine.py", line 4, in <module>
    from voiceModels import rvcGenerator
  File "C:\Users\gabri\Desktop\IAStreameur-main\voiceModels\rvcGenerator.py", line 6, in <module>
    from rvcLib.infer_pack.models import (
  File "C:\Users\gabri\Desktop\IAStreameur-main\voiceModels\rvcLib\infer_pack\models.py", line 6, in <module>
    from lib.infer_pack import modules
ModuleNotFoundError: No module named 'lib.infer_pack'
```

I'm trying to run main.py but I'm facing this error. Checked the `C:\Users\gabri\AppData\Local\Programs\Python\Python310\Lib\site-packages\xformers\_C.pyd` path to see if it was there and it was, tried uninstalling xformers and reinstalling, still facing this problem. Do you know what it could be, thank you!

**Comment by Snowad14** [comment]
This does not come from xformers, it seems that RVC doesn't recognize the right path, it's weird but it works fine for me.

**Comment by mopoIo** [comment]
Is there a way to remove RVC? I'm using ElevenLabs so I don't mind this bug if I can get rid of it

**Comment by Snowad14** [comment]
In "ttsEngine.py" remove "from voiceModels import rvcGenerator".
